// GENERATED by tools/bake_fonts.py -- do not edit by hand.
// Fonts compiled into the binary so the client needs no font files
// at runtime and does not depend on C:/Windows/Fonts.
#pragma once

#include <cstddef>

namespace ms
{
	struct EmbeddedFont
	{
		const char* name;
		const unsigned char* data;
		unsigned int size;
	};

	// Returns nullptr when the name is not baked in.
	const EmbeddedFont* find_embedded_font(const char* name);
}
